Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,33 +26,64 @@ jobs:
       uses: actions/cache@v1
       with:
         path: .build
-        key: build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('Package.*') }}
+        key: build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('Package.*') }}-${{ hashFiles('Sources/**/*.swift') }}
         restore-keys: |
+          build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('Package.*') }}-
           build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-
           build-${{ github.workspace }}-${{ runner.os }}-
           build-${{ github.workspace }}-
     - uses: YOCKOW/Action-setup-swift@master
       with:
         swift-version: '5.1.4'
+    - name: Try to build products with debug mode.
+      run: |
+        swift build --configuration debug -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+        if [ $? != 0 ]; then
+          echo "Failed to build products with debug mode."
+          rm -rf $(cd .build/debug && pwd -P)
+        fi
+      continue-on-error: true
+    - name: Try to build products with release mode.
+      run: |
+        swift build --configuration release -Xswiftc -enable-testing -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+        if [ $? != 0 ]; then
+          echo "Failed to build products with release mode."
+          rm -rf $(cd .build/release && pwd -P)
+        fi
+      continue-on-error: true
     - name: Test with debug mode.
       run: swift test --configuration debug -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
     - name: Test with release mode.
       run: swift test --configuration release -Xswiftc -enable-testing -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+
   test-updater:
     runs-on: macOS-latest
+    env:
+      UPDATER_PACKAGE_ROOT: utils/SwiftUnicodeSupplementUpdater
     steps:
     - uses: actions/checkout@v2
     - name: Use a cache for ".build" directory.
+      env:
+        UPDATER_PACKAGE_MANIFEST: ${{ env.UPDATER_PACKAGE_ROOT }}/Package.*
+        UPDATER_PACKAGE_SOURCES: ${{ env.UPDATER_PACKAGE_ROOT }}/Sources/**/*.swift
       uses: actions/cache@v1
       with:
-        path: utils/SwiftUnicodeSupplementUpdater/.build
-        key: updater_build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('utils/SwiftUnicodeSupplementUpdater/Package.*') }}
+        path: .build
+        key: build-${{ github.workspace }}-${{ runner.os }}-${{ hashFiles(env.UPDATER_PACKAGE_MANIFEST) }}-${{ hashFiles(env.UPDATER_PACKAGE_SOURCES) }}
         restore-keys: |
-          updater_build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-
-          updater_build-${{ github.workspace }}-${{ runner.os }}-
-          updater_build-${{ github.workspace }}-
+          build-${{ github.workspace }}-${{ runner.os }}-${{ hashFiles(env.UPDATER_PACKAGE_MANIFEST) }}-
+          build-${{ github.workspace }}-${{ runner.os }}-
+          build-${{ github.workspace }}-
     - uses: YOCKOW/Action-setup-swift@master
       with:
-        swift-version: '5.1.4'
+        swift-version: '5.1.3'
+    - name: Try to build products with debug mode.
+      run: |
+        swift build --configuration debug --build-path .build --package-path $UPDATER_PACKAGE_ROOT
+        if [ $? != 0 ]; then
+          echo "Failed to build products with debug mode."
+          rm -rf $(cd .build/debug && pwd -P)
+        fi
+      continue-on-error: true
     - name: Test with debug mode.
-      run: swift test --configuration debug --package-path utils/SwiftUnicodeSupplementUpdater
+      run: swift test --configuration debug --build-path .build --package-path $UPDATER_PACKAGE_ROOT
